# version: "3.9"

services:
  db:
    image: postgres:15
    container_name: sso_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sso
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  migrate:
    image: migrate/migrate
    depends_on:
      - db
    command: [
      "-path", "/migrations",
      "-database", "postgres://postgres:postgres@db:5432/sso?sslmode=disable",
      "up"
    ]
    volumes:
      - ./migrations:/migrations

  sso:
    build: .
    container_name: sso_service
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=sso
      - DB_SSLMODE=disable
    volumes:
      - ./config:/app/config:ro   # абсолютный путь внутри контейнера
    ports:
      - "50051:50051"
    depends_on:
      - db
      - migrate

volumes:
  db_data:
