# version: "3.9"

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"

  db:
    image: postgres:15
    container_name: sso_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sso
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  migrate-up:
    image: migrate/migrate
    depends_on:
      - db
    command: [
      "-path", "/migrations",
      "-database", "postgres://postgres:postgres@db:5432/sso?sslmode=disable",
      "up"
    ]
    volumes:
      - ./migrations:/migrations

  migrate-down:
    image: migrate/migrate
    depends_on:
      - db
    command: [
      "-path", "/migrations",
      "-database", "postgres://postgres:postgres@db:5432/sso?sslmode=disable",
      "down"
    ]
    volumes:
      - ./migrations:/migrations

  sso:
    build: .
    container_name: sso_service
    volumes:
      - ./config:/app/config:ro
    ports:
      - "50051:50051"
      - "8080:8080"
    depends_on:
      - db
      - migrate-up
      - redis

volumes:
  db_data:
