server:
  grpc_port: 50051
  http_port: 8080

database:
  host: sso_db
  port: 5432
  user: postgres
  password: postgres
  dbname: sso
  sslmode: disable

auth:
  secret: 186534kol

redis:
  addr: "redis:6379"
  password: 
  limit: 5
